### ISSUE TITLE
Need a hint for tryParseAs<'t>

### ISSUE THREAD

**Issue by pkese** [Zaid-Ajaj/FSharp.SimpleJson#1]
Hi

Fable.SimpleJson side of this library has `Json.tryParseAs<'t>` which this library (FSharp.SimpleJson) is lacking.

I know that `tryParseAs` in javascript has a trivial implementation whereas a full dotnet one is much harder to implement. But I guess it must be implemented somewhere, because Fable.Remoting does provide seamless deserialization.

Could you possibly give me a hint on how to implement generic deserialization from SimpleJson to target type?

Thanks

**Comment by Zaid-Ajaj** [comment]
Hello @pkese

> I guess it must be implemented somewhere, because Fable.Remoting does provide seamless deserialization.

Fable.Remoting uses `Fable.Remoting.Json` to handle the deserialization of F# types, it is implemented [here](https://github.com/Zaid-Ajaj/Fable.Remoting/tree/master/Fable.Remoting.Json) and is available on nuget as a standalone package, so if you are looking for a deserializer, then this is what you want.

This was originally `FableConverter` library that Fable provided in the early days but adapted over the years to accommodate for Fable changes as well as changes in Fable.SimpleJson 

> For example [this piece](https://github.com/Zaid-Ajaj/Fable.Remoting/blob/master/Fable.Remoting.Json/FableConverter.fs#L263-L269) of code that reconstructs `int64` from `{ high, low, signed }` components where Fable couldn't properly serialize `int64` to a number or string (could be fixed now, idk tbh) 

This library however was a little failed experiment where I tried to get rid of the Newtonsoft.Json dependency in Fable.Remoting but was harder than I expected because of preserving the runtime types in dotnet so I abandoned the project at the moment and left only the `Json` helper type in it. 

> Could you possibly give me a hint on how to implement generic deserialization from SimpleJson to target type?

If you start with the source code in `Fable.Remoting.Json` and combine it with the `Json` type from this library, you can adapt it to build a generic deserialization but you will only be reinventing the wheel as Fable.Remoting.Json already does the thing. The only upside of doing this might be that you will probably end with a more readable code because currently the code is a bit of a mess
