### ISSUE TITLE
open FSharp.SimpleJson vs open SimpleJson

### ISSUE THREAD

**Issue by 0x53A** [Zaid-Ajaj/FSharp.SimpleJson#3]
In the documentation it says to ``open FSharp.SimpleJson``, but in the source code it is just 

https://github.com/Zaid-Ajaj/FSharp.SimpleJson/blob/0299d51aa883e10753c536193c52dca577dda3db/FSharp.SimpleJson/SimpleJson.fs#L1

I would have sent a PR instead of complaining in an issue, but I don't know which one is correct, if the documentation or the source should be changed :D

(I assume the source should change to match Fable.SimpleJson, but that would be a breaking change.)

**Comment by Zaid-Ajaj** [comment]
Hi @0x53A, actually I am thinking of archiving this library 😅 despite the name, it is not the .NET counterpart of Fable.SimpleJson (that is Fable.Remoting.Json). This was an attempt as building a dependency-free JSON deserializer for .NET just like Fable.SimpleJson but it didn't really work out. 

if you are interested in the library, please send the PR and I will merge and publish but otherwise I don't have any development plans for this repository to be honest

**Comment by 0x53A** [comment]
> despite the name, it is not the .NET counterpart of Fable.SimpleJson

Yeah I did assume that, the name was a bit confusing. :D 

I needed a library for generic json parsing on the server-side, and since Fable.SimpleJson works good, I thought to just also use this on the server.

Then I'll look into using Newtonsoft with Fable.Remoting.Json, that feels a little more future-safe than using this.

Thanks!
